[tools]
node = "20.11.0"

[tasks.ci]
depends = ["lint:*", "test:*"]

[tasks."lint:*"]
run = "echo 'Lint skipped for now'"

[tasks."test:*"]
run = "echo 'Tests skipped for now'"

[tasks."install:*"]
run = "echo 'Install skipped for now'"
